sudo: required

language: generic

services:
  - docker

script:
  - docker build -t gregoireweber/drupal-example:latest .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag gregoireweber/drupal-example:latest gregoireweber/drupal-example:"$TRAVIS_BUILD_NUMBER";
      docker push gregoireweber/drupal-example:latest;
      docker push gregoireweber/drupal-example:"$TRAVIS_BUILD_NUMBER";
      docker ps -a;
      docker-compose pull;
      docker-compose up -d;
    fi

before_install:
- openssl aes-256-cbc -K $encrypted_43b1fb194bab_key -iv $encrypted_43b1fb194bab_iv -in docker-certs/key.pem.enc -out docker-certs/key.pem -d